apiVersion: apps/v1
kind: Deployment

metadata:
  name: model-drift
  namespace: ml-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: model-drift

  template:
    metadata:
      labels:
        app: model-drift

    spec:
      containers:
        - name: model-drift

          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPOSITORY}/model-drift:${IMAGE_TAG}

          imagePullPolicy: Always

          ports:
            - containerPort: 8001

          env:
            - name: MODEL_NAME
              value: "default-model"

            - name: PREDICTION_LOG_DIR
              value: "/app/logs"

          volumeMounts:
            - name: prediction-logs
              mountPath: /app/logs

      volumes:
        - name: prediction-logs
          emptyDir: {}
