apiVersion: v1

kind: LimitRange

metadata:
  name: ml-api-limits
  namespace: ml-api

spec:
  limits:

  - default:

      cpu: 500m

      memory: 512Mi

    defaultRequest:

      cpu: 200m

      memory: 256Mi

    type: Container
