apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: iris-api-rules
  namespace: monitoring
spec:
  groups:
    - name: iris-api
      interval: 30s

      rules:

      - alert: IrisAPIDown
        expr: up{job="iris-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Iris API Down
          description: Iris API is unreachable.

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes{job="iris-api"} > 500000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High Memory Usage
          description: Iris API is using more than 500 MB memory.

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total{job="iris-api"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU Usage
          description: CPU usage is above 80%.

      - alert: HighRequestRate
        expr: rate(http_requests_total{job="iris-api"}[1m]) > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High Request Rate
          description: API is receiving more than 100 requests/sec.

      - alert: HighErrorRate
        expr: |
          sum(rate(http_requests_total{job="iris-api",status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{job="iris-api"}[5m]))
          > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: High Error Rate
          description: More than 5% of requests are failing.

      - alert: HighLatencyP95
        expr: |
          histogram_quantile(
            0.95,
            sum(rate(http_request_duration_seconds_bucket{job="iris-api"}[5m])) by (le)
          ) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High Latency
          description: P95 latency is above 500 ms.

      - alert: PodRestarting
        expr: increase(kube_pod_container_status_restarts_total{namespace="ml-api"}[15m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Pod Restarting
          description: A pod restarted during the last 15 minutes.

      - alert: PodNotReady
        expr: kube_pod_status_ready{namespace="ml-api",condition="true"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Pod Not Ready
          description: One or more Iris API pods are not Ready.
