apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: ml-api-rules
  namespace: monitoring

spec:
  groups:

  - name: ml-platform.rules

    rules:

    - alert: MLAPIDown

      expr: up{job="ml-api"} == 0

      for: 1m

      labels:
        severity: critical

      annotations:
        summary: ML API Down

        description: ML API has not responded for more than one minute.
