apiVersion: v1
kind: ConfigMap

metadata:
  name: mlflow-config
  namespace: mlflow

data:
  CLOUD_SQL_HOST: "${CLOUD_SQL_HOST}"
  CLOUD_SQL_PORT: "${CLOUD_SQL_PORT}"
  ARTIFACT_ROOT: "${ARTIFACT_ROOT}"
