apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-sa
  namespace: mlflow
  annotations:
    iam.gke.io/gcp-service-account: mlflow-sa@project-cd87c2b0-43f1-4451-809.iam.gserviceaccount.com
