apiVersion: apps/v1
kind: Deployment

metadata:
  name: ml-api
  namespace: ml-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ml-api

  template:
    metadata:
      labels:
        app: ml-api

    spec:
      serviceAccountName: ml-api

      containers:
        - name: api

          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/api:${IMAGE_TAG}

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlflow.svc.cluster.local:5000"
