apiVersion: apps/v1
kind: Deployment

metadata:
  name: iris-api
  namespace: ml-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: iris-api

  template:
    metadata:
      labels:
        app: iris-api

    spec:
      serviceAccountName: iris-api
      containers:

      - name: api

        image: us-central1-docker.pkg.dev/project-cd87c2b0-43f1-4451-809/mlops-repo/api:v2

        ports:
        - containerPort: 8000

        env:

        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.mlflow.svc.cluster.local:5000"
